Config = {}

Config.PermCops = "police.heist"	-- Cops permission
Config.MinCops = 5					-- Amount of cops required to start heist
Config.mincash = 1000 				-- Minimum amount of cash a pile holds
Config.maxcash = 5000 				-- Maximum amount of cash a pile can hold
Config.black = true 				-- Enable this if you want blackmoney as a reward
Config.enablesound = true 			-- Enables bank alarm sound
Config.cooldown = 3600 				-- Amount of time to do the heist again in Seconds Default: (30min)
Config.vaulttime = 120				-- Amount of time to vault door close

Config.items = { -- Items
	thermal = "thermal_charge",
	laptop = "laptop_h",
	lockpick = "lockpick",
	id_card = "id_card",
	diamond = "dia_box",
	gold = "gold_bar",
	dirty_money = "dirty_money"
}

Config.text = { -- Texts
	loudstart = "[~g~E~w~] Start et ~g~HØJT~w~ Bankrøveri",
	silentstart = "[~g~E~w~] Start et ~g~STILLE~w~ Bankrøveri",
	usecard = "[~g~E~w~] Brug ID Kort",
	usethermal = "[~g~E~w~] Brug Thermal Charge",
	usehack = "[~g~E~w~] Hack Sikkerheds Panel",
	uselockpick = "[~g~E~w~] Brug Lockpick",
	usesearch = "[~g~E~w~] Søg",
	lootcash= "[~g~E~w~] Tag Pengene",
	lootgold = "[~g~E~w~] Tag Guldet",
	lootdia = "[~g~E~w~] Tag Diamanterne",
	card = "Bruger ID Kortet",
	thermal = "Planter Thermal Charge",
	burning = "Smelter Låsen",
	lockpick = "Dirker Låsen Op",
	using = "Panelbehandling",
	used = "Processen er afsluttet.",
	stage_complete = "afsluttet.",
	stage = "Niveau",
	search = "Søger",
	hacking = "Hacker",
	melted = "Dørlås smeltet.",
	hacked = "Hack afsluttet.",
	unlocked = "Dør låst op.",
	nothing = "Intet fundet.",
	found = "Du fandt et ID-kort.",
	time = "Resterende: ",
	hackconnect = "Åbn Min computer og naviger til HackConnect.exe",
	ip = "Find IP-adressen...",
	password = "Find adgangskoden...",
	bruteforce = "Kør BruteForce.exe",
	vaulttime = "Du har "..Config.vaulttime.." sekunder tilbage indtil der kommer giftige gaser ud.",
	vaultclose = "Bankdøren lukkes automatisk om 60 sekunder!",
	vaultclose2 = "BANKDØR LUKKES!",
	stole = "Du stjal",
	alarm = "National Bankens alarm er udløst!",
	unlockdoor = "[~g~E~w~] Lås døren op",
	lockdoor = "[~g~E~w~] Lås døren",
	nolaptop = "Du har ikke en hacker-bærbar.",
	noidcard = "Du har ikke et ID-kort.",
	nothermal = "Du har ingen thermal charges.",
	nolockpick = "Du har ingen lockpicks.",
	mincops = "Der skal mindst være "..Config.MinCops.." politi i byen.",
	timeleft = "tilbage til næste røveri.",
	alreadyrobbed = "Banken bliver røvet i øjeblikket.",
	syshack = "System hacking..."
}