RegisterNetEvent("fg-inventory:joint")
AddEventHandler("fg-inventory:joint", function()
	local Ped = GetPlayerPed(-1)
	--TaskPlayAnim(PlayerPedId(), 'dead', 'dead_a', 1.0, 0.0, -1, 9, 9, 1, 1, 1)
	TaskStartScenarioInPlace(Ped, "WORLD_HUMAN_SMOKING_POT", 0, true)
	TriggerServerEvent("fg-inventory:joint")
	Citizen.Wait(5000)
end)

RegisterNetEvent('olsen_attachments:extendedsns2')
AddEventHandler('olsen_attachments:extendedsns2', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Extended Clip...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_SNSPISTOL"), GetHashKey("COMPONENT_SNSPISTOL_CLIP_02"))
end)

RegisterNetEvent('olsen_attachments:extendedpistol')
AddEventHandler('olsen_attachments:extendedpistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Extended Clip...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_PISTOL"), GetHashKey("COMPONENT_PISTOL_CLIP_02"))
end)

RegisterNetEvent('olsen_attachments:supppistol')
AddEventHandler('olsen_attachments:supppistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Suppressor...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_PISTOL"), GetHashKey("COMPONENT_AT_PI_SUPP_02"))
end)

RegisterNetEvent('olsen_attachments:skinpistol')
AddEventHandler('olsen_attachments:skinpistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Skinnet...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_PISTOL"), GetHashKey("COMPONENT_PISTOL_VARMOD_LUXE"))
end)

RegisterNetEvent('olsen_attachments:extendedheavypistol')
AddEventHandler('olsen_attachments:extendedheavypistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Extended Clip...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_HEAVYPISTOL"), GetHashKey("COMPONENT_HEAVYPISTOL_CLIP_02"))
end)

RegisterNetEvent('olsen_attachments:suppheavypistol')
AddEventHandler('olsen_attachments:suppheavypistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Suppressor...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_HEAVYPISTOL"), GetHashKey("COMPONENT_AT_PI_SUPP"))
end)

RegisterNetEvent('olsen_attachments:extended50pistol')
AddEventHandler('olsen_attachments:extended50pistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Extended Clip...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_PISTOL50"), GetHashKey("COMPONENT_PISTOL50_CLIP_02"))
end)

RegisterNetEvent('olsen_attachments:supp50pistol')
AddEventHandler('olsen_attachments:supp50pistol', function()
    SetEntityHeading(ply, 48.975063323975)
    exports['ac_progressbar']:startUI(2000, "Finder Suppressor...")
    SetEntityHeading(ply, 48.975063323975)
    GiveWeaponComponentToPed(PlayerPedId(), GetHashKey("WEAPON_PISTOL50"), GetHashKey("COMPONENT_AT_AR_SUPP_02"))
end)

--- [ MEDICAL ITEMS ] ---
RegisterNetEvent("fg-inventory:fentanyl")
AddEventHandler("fg-inventory:fentanyl", function()
  SetEntityHealth(PlayerPedId(), GetEntityHealth(PlayerPedId()) + 100) 
end)

RegisterNetEvent("fg-inventory:panodil")
AddEventHandler("fg-inventory:panodil", function()
  SetEntityHealth(PlayerPedId(), GetEntityHealth(PlayerPedId()) + 10) 
end)

RegisterNetEvent("fg-inventory:bandage")
AddEventHandler("fg-inventory:bandage", function()
  SetEntityHealth(PlayerPedId(), GetEntityHealth(PlayerPedId()) + 25) 
end)
--- [ AMMO ] ---
RegisterNetEvent("fg-inventory:PISTOL_AMMO")
AddEventHandler("fg-inventory:PISTOL_AMMO", function()
    local Ped = GetPlayerPed(-1)
    AddAmmoToPed(Ped, "WEAPON_PISTOL", 1)
end)

RegisterNetEvent("fg-inventory:SNIPER_AMMO")
AddEventHandler("fg-inventory:SNIPER_AMMO", function()
    local Ped = GetPlayerPed(-1)
    AddAmmoToPed(Ped, "WEAPON_SNIPERRIFLE", 1)
end)

RegisterNetEvent("fg-inventory:SMG_AMMO")
AddEventHandler("fg-inventory:SMG_AMMO", function()
    local Ped = GetPlayerPed(-1)
    AddAmmoToPed(Ped, "WEAPON_SMG", 1)
end)

RegisterNetEvent("fg-inventory:RIFLE_AMMO")
AddEventHandler("fg-inventory:RIFLE_AMMO", function()
    local Ped = GetPlayerPed(-1)
    AddAmmoToPed(Ped, "WEAPON_CARBINERIFLE", 1)
end)

--- [ NORMAL WEAPONS ] ---
RegisterNetEvent('fg-inventory:WEAPON_KNIFE')
AddEventHandler('fg-inventory:WEAPON_KNIFE', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_KNIFE", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_SWITCHBLADE')
AddEventHandler('fg-inventory:WEAPON_SWITCHBLADE', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_SWITCHBLADE", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_HATCHET')
AddEventHandler('fg-inventory:WEAPON_HATCHET', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_HATCHET", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_MACHETE')
AddEventHandler('fg-inventory:WEAPON_MACHETE', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_MACHETE", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_BAT')
AddEventHandler('fg-inventory:WEAPON_BAT', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_BAT", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_CROWBAR')
AddEventHandler('fg-inventory:WEAPON_CROWBAR', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_CROWBAR", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_GOLFCLUB')
AddEventHandler('fg-inventory:WEAPON_GOLFCLUB', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_GOLFCLUB", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_WRENCH')
AddEventHandler('fg-inventory:WEAPON_WRENCH', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_WRENCH", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_HAMMER')
AddEventHandler('fg-inventory:WEAPON_HAMMER', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_HAMMER", 0, false, false)
end)
--- [ BLACK MARKET ] ---
RegisterNetEvent('fg-inventory:WEAPON_KNUCKLE')
AddEventHandler('fg-inventory:WEAPON_KNUCKLE', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_KNUCKLE", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_PISTOL')
AddEventHandler('fg-inventory:WEAPON_PISTOL', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_PISTOL", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_PISTOL50')
AddEventHandler('fg-inventory:WEAPON_PISTOL50', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_PISTOL50", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_HEAVYPISTOL')
AddEventHandler('fg-inventory:WEAPON_HEAVYPISTOL', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_HEAVYPISTOL", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_SNSPISTOL')
AddEventHandler('fg-inventory:WEAPON_SNSPISTOL', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_SNSPISTOL", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_DOUBLEACTION')
AddEventHandler('fg-inventory:WEAPON_DOUBLEACTION', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_DOUBLEACTION", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_MICROSMG')
AddEventHandler('fg-inventory:WEAPON_MICROSMG', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_MICROSMG", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_MUSKET')
AddEventHandler('fg-inventory:WEAPON_MUSKET', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_MUSKET", 0, false, false)
end)
--- [ POLITIETS VÅBEN ] ---
RegisterNetEvent('fg-inventory:WEAPON_FLASHLIGHT')
AddEventHandler('fg-inventory:WEAPON_FLASHLIGHT', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_FLASHLIGHT", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_NIGHTSTICK')
AddEventHandler('fg-inventory:WEAPON_NIGHTSTICK', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_NIGHTSTICK", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_STUNGUN')
AddEventHandler('fg-inventory:WEAPON_STUNGUN', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_STUNGUN", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_COMBATPISTOL')
AddEventHandler('fg-inventory:WEAPON_COMBATPISTOL', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_COMBATPISTOL", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_SMG')
AddEventHandler('fg-inventory:WEAPON_SMG', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_SMG", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_MINISMG')
AddEventHandler('fg-inventory:WEAPON_MINISMG', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_MINISMG", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_HEAVYSNIPER')
AddEventHandler('fg-inventory:WEAPON_HEAVYSNIPER', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_HEAVYSNIPER", 0, false, false)
end)

RegisterNetEvent('fg-inventory:WEAPON_CARBINERIFLE')
AddEventHandler('fg-inventory:WEAPON_CARBINERIFLE', function()
    GiveWeaponToPed(GetPlayerPed(-1), "WEAPON_CARBINERIFLE", 0, false, false)
end)