local cfg = {}

cfg.showgarage = {
  vehicles = {
	{name = "Blista", costs = 50000, description = {}, model = "blista"},
	{name = "Brioso R/A", costs = 75000, description = {}, model = "brioso"},
	{name = "Dilettante", costs = 50000, description = {}, model = "dilettante"},
	{name = "Futo", costs = 112500, description = {}, model = "futo"},
	{name = "Issi", costs = 60000, description = {}, model = "issi2"},
	{name = "Prairie", costs = 75000, description = {}, model = "prairie"},
	{name = "Rhapsody", costs = 50000, description = {}, model = "rhapsody"},
	{name = "Emperor", costs = 40000, description = {}, model = "emperor"},
	{name = "Issi Classic", costs = 40000, description = {}, model = "issi3"},
	{name = "Panto", costs = 60000, description = {}, model = "panto"},
	{name = "Issi 7", costs = 500000, description = {}, model = "issi7"},
	{name = "Cognoscenti Cabrio", costs = 750000, description = {}, model = "cogcabrio"},
	{name = "F620", costs = 775000, description = {}, model = "f620"},
	{name = "Felon GT", costs = 650000, description = {}, model = "felon2"},
	{name = "Jackal", costs = 650000, description = {}, model = "jackal"},
	{name = "Oracle", costs = 450000, description = {}, model = "oracle"},
	{name = "Oracle XS", costs = 500000, description = {}, model = "oracle2"},
	{name = "Sentinel", costs = 435000, description = {}, model = "sentinel"},
	{name = "Sentinel XS", costs = 430000, description = {}, model = "sentinel2"},
	{name = "Übermacht Sentinel Classic", costs = 1250000, description = {}, model = "sentinel3"},
	{name = "Windsor", costs = 1400000, description = {}, model = "windsor"},
	{name = "Windsor Drop", costs = 1300000, description = {}, model = "windsor2"},
	{name = "Zion", costs = 600000, description = {}, model = "zion"},
	{name = "FlashGT", costs = 450000, description = {}, model = "flashgt"},
	{name = "Zion Cabrio", costs = 620000, description = {}, model = "zion2"},
	{name = "Specter", costs = 1300000, description = {}, model = "specter"},
	{name = "Specter CTM", costs = 1400000, description = {}, model = "specter2"},
	{name = "Monroe", costs = 575000, description = {}, model = "monroe"},
	{name = "Ubermacht Zion", costs = 415000, description = {}, model = "zion3"},
	{name = "Nebula", costs = 300000, description = {}, model = "nebula"},
	{name = "Banshee", costs = 675000, description = {}, model = "banshee"},
	{name = "Buffalo", costs = 620000, description = {}, model = "buffalo"},
	{name = "Buffalo S", costs = 650000, description = {}, model = "buffalo2"},
	{name = "Carbonizzare", costs = 1200000, description = {}, model = "carbonizzare"},
	{name = "Coquette", costs = 900000, description = {}, model = "coquette"},
	{name = "Furore GT", costs = 850000, description = {}, model = "furoregt"},
	{name = "Fusilade", costs = 675000, description = {}, model = "fusilade"},
	{name = "Hijak Ruston", costs = 650000, description = {}, model = "ruston"},
	{name = "Jester", costs = 3700000, description = {}, model = "jester"},
	{name = "Kuruma", costs = 1500000, description = {}, model = "kuruma"},
	{name = "Lynx", costs = 1440000, description = {}, model = "lynx"},
	{name = "Massacro", costs = 3200000, description = {}, model = "massacro"},
	{name = "Omnis", costs = 1000000, description = {}, model = "omnis"},
	{name = "Penumbra", costs = 650000, description = {}, model = "penumbra"},
	{name = "Schafter V12", costs = 1350000, description = {}, model = "schafter3"},
	{name = "Sultan", costs = 700000, description = {}, model = "sultan"},
	{name = "Sultan RS", costs = 2200000, description = {}, model = "sultanrs"},
	{name = "Feltzer 2", costs = 1500000, description = {}, model = "feltzer2"},
	{name = "Surano", costs = 600000, description = {}, model = "surano"},
	{name = "Tropos", costs = 1350000, description = {}, model = "tropos"},
	{name = "Verkierer", costs = 500000, description = {}, model = "verlierer2"},	
	{name = "Neon", costs = 1900000, description = {}, model = "neon"},	
	{name = "Comet SR", costs = 3500000, description = {}, model = "comet5"},	
	{name = "Comet Custom", costs = 2500000, description = {}, model = "comet3"},	
	{name = "Bestia GTS", costs = 2000000, description = {}, model = "bestiagts"},	
	{name = "Jester(Racecar)", costs = 3000000, description = {}, model = "jester2"},
	{name = "Jester3", costs = 825000, description = {}, model = "jester3"},	
	{name = "Massacro(Racecar)", costs = 2900000, description = {}, model = "massacro2"},	
	{name = "Rapid GT", costs = 2700000, description = {}, model = "rapidgt"},	
	{name = "Rapid GT Convert", costs = 3000000, description = {}, model = "rapidgt2"},	
	{name = "Schlagen GT", costs = 3000000, description = {}, model = "schlagen"},	
	{name = "Pariah", costs = 2100000, description = {}, model = "pariah"},	
	{name = "Khamelion", costs = 1700000, description = {}, model = "khamelion"},	
	{name = "Raptor", costs = 1000000, description = {}, model = "raptor"},	
	{name = "Dominator GTX", costs = 3000000, description = {}, model = "dominator3"},	
	{name = "Elegy", costs = 1800000, description = {}, model = "elegy"},
	{name = "Elegy Turbo", costs = 2400000, description = {}, model = "elegy2"},	
	{name = "Dewbauchee Exemplar", costs = 500000, description = {}, model = "exemplar"},
	{name = "Dewbauchee Seven-70", costs = 600000, description = {}, model = "seven70"},
	{name = "Benefactor Schwartzer", costs = 400000, description = {}, model = "schwarzer"},	
	{name = "Weeny Issi", costs = 3500000, description = {}, model = "issi7"},
	{name = "Jugular", costs = 5500000, description = {}, model = "jugular"},	
	{name = "Casco", costs = 700000, description = {}, model = "casco"},
	{name = "Coquette Classic", costs = 900000, description = {}, model = "coquette2"},
	{name = "Pigalle", costs = 400000, description = {}, model = "pigalle"},
	{name = "Stinger", costs = 800000, description = {}, model = "stinger"},
	{name = "Stinger GT", costs = 900000, description = {}, model = "stingergt"},
	{name = "Stirling GT", costs = 710000, description = {}, model = "feltzer3"},
	{name = "Z-Type", costs = 1000000, description = {}, model = "ztype"},
	{name = "Btype 3", costs = 1100000, description = {}, model = "btype3"},		
	{name = "Retinue", costs = 350000, description = {}, model = "retinue"},
	{name = "Torero", costs = 900000, description = {}, model = "torero"},
	{name = "Cheetah Classic", costs = 950000, description = {}, model = "cheetah2"},
	{name = "Hermes", costs = 600000, description = {}, model = "hermes"},
	{name = "Rapid GT Classic", costs = 550000, description = {}, model = "rapidgt3"},
	{name = "Michelli GT-", costs = 160000, description = {}, model = "michelli"},
	{name = "Fagaloa", costs = 200000, description = {}, model = "fagaloa"},
	{name = "Karin 190z", costs = 400000, description = {}, model = "z190"},
	{name = "Tyrant", costs = 6250000, description = {}, model = "tyrant"},
	{name = "Osiris", costs = 4500000, description = {}, model = "osiris"},
	{name = "Taipan", costs = 5450000, description = {}, model = "taipan"},
	{name = "Zentorno", costs = 7500000, description = {}, model = "zentorno"},
	{name = "Vacca", costs = 5500000, description = {}, model = "vacca"},
	{name = "Tempesta", costs = 7200000, description = {}, model = "tempesta"},
	{name = "Reaper", costs = 6750000, description = {}, model = "reaper"},
	{name = "Entity XF", costs = 6500000, description = {}, model = "entityxf"},
	{name = "Grotti Itali", costs = 12500000, description = {}, model = "italigto"},
	{name = "Übermacht SC1", costs = 3100000, description = {}, model = "sc1"},
	{name = "Krieger", costs = 8500000, description = {}, model = "krieger"},
	{name = "Neo", costs = 9000000, description = {}, model = "neo"},
	{name = "Paragon", costs = 8500000, description = {}, model = "paragon"},
	{name = "Zorrusso", costs = 5000000, description = {}, model = "zorrusso"},
	{name = "Emerus", costs = 11000000, description = {}, model = "emerus"},
	{name = "Locust", costs = 6000000, description = {}, model = "locust"},
	{name = "Thrax", costs = 10000000, description = {}, model = "thrax"},
	{name = "Blade", costs = 325000, description = {}, model = "blade"},
	{name = "Buccaneer", costs = 250000, description = {}, model = "buccaneer"},
	{name = "Chino", costs = 225000, description = {}, model = "chino"},
	{name = "Coquette BlackFin", costs = 695000, description = {}, model = "coquette3"},
	{name = "Dominator", costs = 625000, description = {}, model = "dominator"},
	{name = "Dukes", costs = 575000, description = {}, model = "dukes"},
	{name = "Faction", costs = 545000, description = {}, model = "faction"},
	{name = "Ruiner", costs = 375000, description = {}, model = "ruiner"},
	{name = "Voodoo", costs = 325000, description = {}, model = "voodoo"},
	{name = "Hotknife", costs = 610000, description = {}, model = "hotknife"},
	{name = "Ratloader V2", costs = 345000, description = {}, model = "ratloader2"},
	{name = "Impaler", costs = 475000, description = {}, model = "impaler"},
	{name = "Deviant", costs = 600000, description = {}, model = "deviant"},
	{name = "Slamvan", costs = 395000, description = {}, model = "slamvan"},
	{name = "Nightshade", costs = 475000, description = {}, model = "nightshade"},
	{name = "Picador", costs = 400000, description = {}, model = "picador"},
	{name = "Tampa", costs = 660000, description = {}, model = "tampa"},
	{name = "Ellie", costs = 610000, description = {}, model = "ellie"},
	{name = "Virgo", costs = 150000, description = {}, model = "virgo"},
	{name = "Vapid Clique", costs = 625000, description = {}, model = "clique"},
	{name = "Bravado Gauntlet", costs = 500000, description = {}, model = "gauntlet"},
	{name = "Imponte Phoenix", costs = 510000, description = {}, model = "phoenix"},
	{name = "Declasse Tulip", costs = 510000, description = {}, model = "tulip"},
	{name = "Sabre Turbo", costs = 625000, description = {}, model = "sabregt"},
	{name = "Gauntlet Classic", costs = 575000, description = {}, model = "gauntlet3"},
	{name = "Bifta", costs = 75000, description = {}, model = "bifta"},
	{name = "Brawler", costs = 725000, description = {}, model = "brawler"},
	{name = "Dubsta 6x6", costs = 475000, description = {}, model = "dubsta3"},
	{name = "Dune Buggy", costs = 150000, description = {}, model = "dune"},
	{name = "Rebel", costs = 220000, description = {}, model = "rebel2"},
	{name = "Rodhi 2", costs = 85000, description = {}, model = "bodhi2"},
	{name = "Kamacho", costs = 315000, description = {}, model = "kamacho"},
	{name = "Riata", costs = 325000, description = {}, model = "riata"},
	{name = "Streiter", costs = 225000, description = {}, model = "streiter"},
	{name = "Blazer", costs = 10000, description = {}, model = "blazer"},
	{name = "Bravado Rumpo Custom", costs = 235000, description = {}, model = "rumpo3"},
	{name = "Canis Mesa Merryweather", costs = 165000, description = {}, model = "mesa3"},
	{name = "Baller", costs = 735000, description = {}, model = "baller"},
	{name = "Cavalcade", costs = 330000, description = {}, model = "cavalcade"},
	{name = "Granger", costs = 665000, description = {}, model = "granger"},
	{name = "Huntley S", costs = 465000, description = {}, model = "huntley"},
	{name = "Landstalker", costs = 83000, description = {}, model = "landstalker"},
	{name = "Radius", costs = 62000, description = {}, model = "radi"},
	{name = "Rocoto", costs = 780000, description = {}, model = "rocoto"},
	{name = "Seminole", costs = 165000, description = {}, model = "seminole"},
	{name = "XLS", costs = 465000, description = {}, model = "xls"},
	{name = "Dubsta", costs = 750000, description = {}, model = "dubsta"},
	{name = "Benefactor Dubsta", costs = 1250000, description = {}, model = "dubsta2"},
	{name = "FQ2", costs = 1000000, description = {}, model = "fq2"},
	{name = "Patriot SUV", costs = 2000000, description = {}, model = "patriot2"},
	{name = "Baller V3", costs = 1600000, description = {}, model = "baller3"},
	{name = "Toros", costs = 3200000, description = {}, model = "toros"},
	{name = "Vapid Contender", costs = 200000, description = {}, model = "contender"},
	{name = "Patriot", costs = 1500000, description = {}, model = "patriot"},
	{name = "Novak", costs = 450000, description = {}, model = "novak"},
	{name = "Hellion", costs = 550000, description = {}, model = "hellion"},
	{name = "Caracara 4x4", costs = 350000, description = {}, model = "caracara2"},
	{name = "Bison", costs = 130000, description = {}, model = "bison"},
	{name = "Bobcat XL", costs = 123000, description = {}, model = "bobcatxl"},
	{name = "Journey", costs = 150000, description = {}, model = "journey"},
	{name = "Minivan", costs = 300000, description = {}, model = "minivan"},
	{name = "Rustvogn", costs = 800000, description = {}, model = "romero"},
	{name = "Paradise", costs = 250000, description = {}, model = "paradise"},
	{name = "Camper", costs = 345000, description = {}, model = "camper"},
	{name = "Rumpo", costs = 130000, description = {}, model = "rumpo"},
	{name = "Surfer", costs = 110000, description = {}, model = "surfer"},
	{name = "Youga", costs = 160000, description = {}, model = "youga"},
	{name = "MoonBeam", costs = 500000, description = {}, model = "moonbeam2"},
	{name = "Asea", costs = 225000, description = {}, model = "asea"},
	{name = "Asterope", costs = 257000, description = {}, model = "asterope"},
	{name = "Ingot", costs = 85000, description = {}, model = "ingot"},
	{name = "Intruder", costs = 250000, description = {}, model = "intruder"},
	{name = "Premier", costs = 210000, description = {}, model = "premier"},
	{name = "Primo", costs = 235000, description = {}, model = "primo"},
	{name = "Primo Custom", costs = 275000, description = {}, model = "primo2"},
	{name = "Regina", costs = 175000, description = {}, model = "regina"},
	{name = "Schafter", costs = 625000, description = {}, model = "schafter2"},
	{name = "Stanier", costs = 100000, description = {}, model = "stanier"},
	{name = "Stratum", costs = 100000, description = {}, model = "stratum"},
	{name = "Stretch", costs = 750000, description = {}, model = "stretch"},
	{name = "Super Diamond", costs = 670000, description = {}, model = "superd"},
	{name = "Surge", costs = 240000, description = {}, model = "surge"},
	{name = "Cheburek", costs = 165000, description = {}, model = "cheburek"},
	{name = "Tailgater", costs = 410000, description = {}, model = "tailgater"},
	{name = "Warrener", costs = 175000, description = {}, model = "warrener"},
	{name = "Washington", costs = 225000, description = {}, model = "washington"},
	{name = "Raiden", costs = 675000, description = {}, model = "raiden"},
	{name = "Cognoscenti", costs = 650000, description = {}, model = "cognoscenti"},
	{name = "Cognoscenti 55", costs = 7000000, description = {}, model = "cog55"},
	{name = "Glendale", costs = 195000, description = {}, model = "glendale"},
	{name = "Weeny Dynasty", costs = 250000, description = {}, model = "dynasty"},
	{name = "Drafter", costs = 680000, description = {}, model = "drafter"},
	{name = "Akuma", costs = 90000, description = {}, model = "akuma"},
	{name = "Bagger", costs = 250000, description = {}, model = "bagger"},
	{name = "Bati 801", costs = 120000, description = {}, model = "bati"},
	{name = "Bati 801RR", costs = 120000, description = {}, model = "bati2"},
	{name = "BF400", costs = 300000, description = {}, model = "bf400"},
	{name = "Carbon RS", costs = 180000, description = {}, model = "carbonrs"},
	{name = "Cliffhanger", costs = 325000, description = {}, model = "cliffhanger"},
	{name = "Double T", costs = 800000, description = {}, model = "double"},
	{name = "Faggio", costs = 13000, description = {}, model = "faggio2"},
	{name = "Gargoyle", costs = 220000, description = {}, model = "gargoyle"},
	{name = "Hakuchou", costs = 650000, description = {}, model = "hakuchou"},
	{name = "Hexer", costs = 120000, description = {}, model = "hexer"},
	{name = "Innovation", costs = 190000, description = {}, model = "innovation"},
	{name = "Nemesis", costs = 120000, description = {}, model = "nemesis"},
	{name = "PCJ-600", costs = 90000, description = {}, model = "pcj"},
	{name = "Ruffian", costs = 210000, description = {}, model = "ruffian"},
	{name = "Sanchez", costs = 80000, description = {}, model = "sanchez"},
	{name = "Thrust", costs = 323000, description = {}, model = "thrust"},
	{name = "Vader", costs = 200000, description = {}, model = "vader"},
	{name = "Vindicator", costs = 600000, description = {}, model = "vindicator"},
	{name = "Nightblade", costs = 400000, description = {}, model = "nightblade"},
	{name = "ZombieChopper", costs = 385000, description = {}, model = "zombieb"},
	{name = "Avarus", costs = 400000, description = {}, model = "avarus"},
	{name = "Sanctus", costs = 2000000, description = {}, model = "sanctus"},
	{name = "Vortex", costs = 800000, description = {}, model = "vortex"},
	{name = "Diabolus Custom", costs = 300000, description = {}, model = "diablous2"},
	{name = "BMX", costs = 2000, description = {}, model = "bmx"},
	{name = "Cruiser", costs = 5000, description = {}, model = "cruiser"},
	{name = "Fixter", costs = 5000, description = {}, model = "fixter"},
	{name = "Scorcher", costs = 9000, description = {}, model = "scorcher"},
	{name = "Tribike 1", costs = 14500, description = {}, model = "tribike"},
	{name = "Tribike 2", costs = 14500, description = {}, model = "tribike2"},
	{name = "Tribike 3", costs = 14500, description = {}, model = "tribike3"},
	{name = "Peyote Gasser", costs = 650000, description = {}, model = "peyote2"},
	{name = "Gauntlet Hellfire", costs = 2250000, description = {}, model = "gauntlet4"},
	{name = "Penetrator", costs = 3000000, description = {}, model = "penetrator"},
	{name = "Cyclone", costs = 7500000, description = {}, model = "cyclone"},
	{name = "Vagner", costs = 5250000, description = {}, model = "vagner"},
	{name = "Voltic", costs = 3750000, description = {}, model = "voltic"},
	{name = "Turismor", costs = 6500000, description = {}, model = "turismor"},
	{name = "Tyrus", costs = 5500000, description = {}, model = "tyrus"},
	{name = "Itali GTB", costs = 6250000, description = {}, model = "italigtb"},
	{name = "X80 Proto", costs = 6000000, description = {}, model = "prototipo"},
	{name = "Pfister 811", costs = 5500000, description = {}, model = "pfister811"},
	{name = "Cheetah", costs = 7750000, description = {}, model = "cheetah"},
	{name = "T20", costs = 8200000, description = {}, model = "t20"},
	{name = "Emperor ETR1", costs = 4750000, description = {}, model = "sheava"},
	{name = "Nero Custom", costs = 6000000, description = {}, model = "nero2"},
	{name = "Vapid FMJ", costs = 7000000, description = {}, model = "fmj"},
	{name = "GP1", costs = 5500000, description = {}, model = "gp1"},
	{name = "Canis Mesa", costs = 300000, description = {}, model = "mesa"},
	{name = "Rebel", costs = 275000, description = {}, model = "rebel"},
	{name = "Kalahari", costs = 125000, description = {}, model = "kalahari"},
	{name = "Lectro", costs = 175000, description = {}, model = "lectro"},
	{name = "Defiler", costs = 200000, description = {}, model = "defiler"},
	{name = "Daemon", costs = 225500, description = {}, model = "daemon"},
	{name = "Enduro", costs = 160000, description = {}, model = "enduro"},
	{name = "Pegassi", costs = 350000, description = {}, model = "esskey"},
	{name = "FCR 1000 Custom", costs = 200000, description = {}, model = "fcr2"},
	{name = "FCR 1000", costs = 180000, description = {}, model = "fcr"},
	{name = "Manchez", costs = 150000, description = {}, model = "manchez"},
	{name = "Sovereign", costs = 275000, description = {}, model = "sovereign"},
	{name = "Ruffian", costs = 150000, description = {}, model = "ruffian"},
	{name = "PCJ 600", costs = 120000, description = {}, model = "pcj"},
	{name = "Vader", costs = 125000, description = {}, model = "vader"},
	{name = "Sultan Classic", costs = 1200000, description = {}, model = "sultan2"},
	{name = "Club", costs = 70000, description = {}, model = "club"},
	{name = "Coquette D10", costs = 6000000, description = {}, model = "coquette4"},
	{name = "Beater Dukes", costs = 2000000, description = {}, model = "dukes3"},
	{name = "Glendale Custom", costs = 1000000, description = {}, model = "glendale2"},
	{name = "Gauntlet Classic 2", costs = 2000000, description = {}, model = "gauntlet5"},
	{name = "Landstalker XL", costs = 2000000, description = {}, model = "landstalker2"},
	{name = "Albany Manana", costs = 300000, description = {}, model = "manana2"},
	{name = "Vapid Peyote", costs = 750000, description = {}, model = "peyote3"},
	{name = "Seminole Frontier", costs = 400000, description = {}, model = "seminole2"},
	{name = "Tigon", costs = 3000000, description = {}, model = "tigon"},
	{name = "Yosemite Rancher", costs = 500000, description = {}, model = "yosemite3"},
	{name = "Youga Classic 4x4", costs = 300000, description = {}, model = "youga3"},
  }
}

return cfg